name: Lint

on: [push, pull_request]

jobs:

  javascript:
    name: Javascript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm --version
      - run: npm ci
      - run: npm run eslint
      - run: npm run prettier:ci

  php:
    name: PHP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - run: find . -type f -name '*.php' -exec php -l {} \;

  yaml:
    name: Yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibiqlik/action-yamllint@v3
